AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Backend para enviar correo de SuperClub
  
Globals:
  Function:
    Timeout: 600
    Handler: app.handler
    Runtime: nodejs14.x
    MemorySize: 512

Parameters:
  SendgridApiKey:
    Type: String
    Description: API Key para Sendgrid

Resources:
  SuperClubAPI:
    Type: AWS::Serverless::Api
    Properties:
      Cors:
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      StageName: prod

  EnviarCorreoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: enviar_correo_superclub/
      Environment:
        Variables:
          SendgridApiKey: !Ref SendgridApiKey
      Events:
        EnviarCorreo:
          Type: Api
          Properties:
            RestApiId: !Ref SuperClubAPI
            Path: /enviar_correo
            Method: post


